package main

import (
	"strings"
	"testing"
)

func testSplit(t *testing.T, fullname, expectedPkg, expectedRcv, expectedName string, expectedPtrRcv bool) {
	pkg, rcv, name, pointerRcv := splitSubroutine(fullname)
	if pkg != expectedPkg {
		t.Errorf("testSplit(): \nexpected %s\ngot      %s", expectedPkg, pkg)
	}
	if rcv != expectedRcv {
		t.Errorf("testSplit(): \nexpected %s\ngot      %s", expectedRcv, rcv)
	}
	if name != expectedName {
		t.Errorf("testSplit(): \nexpected %s\ngot      %s", expectedName, name)
	}
	if pointerRcv != expectedPtrRcv {
		t.Errorf("testSplit(): \nexpected %v\ngot      %v", expectedPtrRcv, pointerRcv)
	}
}

func TestSplitSubroutine(t *testing.T) {

	testSplit(t, "net.(*dialResult.1).Close", "net", "dialResult.1", "Close", true)
	testSplit(t,"net.(*racer.2).Error", "net", "racer.2", "Error", true)

	testSplit(t, "github.com/minio/minio/cmd.glob..func1", "github.com/minio/minio/cmd", "", "glob..func1", false)

	testSplit(t, "github.com/minio/minio/cmd.adminAPIHandlers.ServiceStatusHandler", "github.com/minio/minio/cmd", "adminAPIHandlers", "ServiceStatusHandler", false)
	testSplit(t, "github.com/minio/minio/cmd.(*adminAPIHandlers).ServiceStatusHandler", "github.com/minio/minio/cmd", "adminAPIHandlers", "ServiceStatusHandler", true)

	testSplit(t, "github.com/minio/minio/cmd.validateLockQueryParams", "github.com/minio/minio/cmd", "", "validateLockQueryParams", false)

	testSplit(t, "github.com/minio/minio/cmd.adminAPIHandlers.ServerInfoHandler.func1", "github.com/minio/minio/cmd", "adminAPIHandlers", "ServerInfoHandler.func1", false)
	testSplit(t, "net/http.(*response).CloseNotify.func1.1", "net/http", "response", "CloseNotify.func1.1", true)

	testSplit(t, "github.com/minio/minio/cmd.(objectAPIHandlers).PutObjectPartHandler-fm", "github.com/minio/minio/cmd", "objectAPIHandlers", "PutObjectPartHandler-fm", false)

	testSplit(t, "github.com/minio/minio/cmd.(fsObjects).(github.com/minio/minio/cmd.isMultipartUpload)-fm", "github.com/minio/minio/cmd", "fsObjects", "(github.com/minio/minio/cmd.isMultipartUpload)-fm", false)
	testSplit(t, "github.com/minio/minio/cmd.(xlObjects).(github.com/minio/minio/cmd.isObject)-fm", "github.com/minio/minio/cmd", "xlObjects", "(github.com/minio/minio/cmd.isObject)-fm", false)
}

func TestParseDisassembly(t *testing.T) {

	lines := strings.Split(disassembly, "\n")

	pkgMap := parseDisassembly(lines)

	rcv, ok := pkgMap["github.com/minio/minio/cmd"]
	if !ok {
		t.Errorf("TestParseDisassembly(): \nexpected %v map entry", "github.com/minio/minio/cmd")
	}

	subs, ok := rcv["adminAPIHandlers"]
	if !ok {
		t.Errorf("TestParseDisassembly(): \nexpected %v map entry", "adminAPIHandlers")
	}

	for i, s := range subs {
		if s.name != "ServerInfoHandler" {
			t.Errorf("TestParseDisassembly(): \nexpected %v function name", "ServerInfoHandler")
		}
		if i == 0 {
			if s.pointerRcv {
				t.Errorf("TestParseDisassembly(): \nexpected value receiver")
			} else if s.autogend {
				t.Errorf("TestParseDisassembly(): \ndid not expect autogenerated function")
			}
		} else if i == 1 {
			if !s.pointerRcv {
				t.Errorf("TestParseDisassembly(): \nexpected pointer receiver")
			} else if !s.autogend {
				t.Errorf("TestParseDisassembly(): \nexpected autogenerated function")
			}

		} else {
			t.Errorf("TestParseDisassembly(): \nunexpected entry: %v", i)
		}
	}
}

const disassembly = `TEXT github.com/minio/minio/cmd.adminAPIHandlers.ServerInfoHandler(SB) /Users/frankw/golang/src/github.com/minio/minio/cmd/admin-handlers.go
        admin-handlers.go:252   0x7f1c0 65488b0c25a0080000      GS MOVQ GS:0x8a0, CX
        admin-handlers.go:252   0x7f1c9 488d4424a0              LEAQ -0x60(SP), AX
        admin-handlers.go:252   0x7f1ce 483b4110                CMPQ 0x10(CX), AX
        admin-handlers.go:252   0x7f1d2 0f86b6030000            JBE 0x7f58e
        admin-handlers.go:252   0x7f1d8 4881ece0000000          SUBQ $0xe0, SP
        admin-handlers.go:252   0x7f1df 4889ac24d8000000        MOVQ BP, 0xd8(SP)
        admin-handlers.go:252   0x7f1e7 488dac24d8000000        LEAQ 0xd8(SP), BP
        admin-handlers.go:254   0x7f1ef 488b8424f8000000        MOVQ 0xf8(SP), AX
        admin-handlers.go:254   0x7f1f7 48890424                MOVQ AX, 0(SP)
        admin-handlers.go:254   0x7f1fb 48c744240800000000      MOVQ $0x0, 0x8(SP)
        admin-handlers.go:254   0x7f204 48c744241000000000      MOVQ $0x0, 0x10(SP)
        admin-handlers.go:254   0x7f20d 48c744241800000000      MOVQ $0x0, 0x18(SP)
        admin-handlers.go:254   0x7f216 48c744242000000000      MOVQ $0x0, 0x20(SP)
        admin-handlers.go:254   0x7f21f 48c744242800000000      MOVQ $0x0, 0x28(SP)
        admin-handlers.go:254   0x7f228 48c744243000000000      MOVQ $0x0, 0x30(SP)
        admin-handlers.go:254   0x7f231 e84a4e0100              CALL github.com/minio/minio/cmd.checkRequestAuthType(SB)
        admin-handlers.go:254   0x7f236 488b442438              MOVQ 0x38(SP), AX
        admin-handlers.go:255   0x7f23b 4885c0                  TESTQ AX, AX
        admin-handlers.go:255   0x7f23e 0f8506030000            JNE 0x7f54a
        admin-handlers.go:261   0x7f244 488b052daa0701          MOVQ 0x107aa2d(IP), AX
        admin-handlers.go:261   0x7f24b 488d0d2ee18b00          LEAQ 0x8be12e(IP), CX
        admin-handlers.go:261   0x7f252 48890c24                MOVQ CX, 0(SP)
        admin-handlers.go:261   0x7f256 4889442408              MOVQ AX, 0x8(SP)
        admin-handlers.go:261   0x7f25b 4889442410              MOVQ AX, 0x10(SP)
        admin-handlers.go:261   0x7f260 e88b2bfcff              CALL runtime.makeslice(SB)
        admin-handlers.go:261   0x7f265 488b442420              MOVQ 0x20(SP), AX
        admin-handlers.go:261   0x7f26a 4889442458              MOVQ AX, 0x58(SP)
        admin-handlers.go:261   0x7f26f 488b4c2418              MOVQ 0x18(SP), CX
        admin-handlers.go:261   0x7f274 48898c2480000000        MOVQ CX, 0x80(SP)
        admin-handlers.go:261   0x7f27c 488b542428              MOVQ 0x28(SP), DX
        admin-handlers.go:261   0x7f281 4889542460              MOVQ DX, 0x60(SP)
        admin-handlers.go:263   0x7f286 488d1d33888c00          LEAQ 0x8c8833(IP), BX
        admin-handlers.go:263   0x7f28d 48891c24                MOVQ BX, 0(SP)
        admin-handlers.go:263   0x7f291 e86a2bf9ff              CALL runtime.newobject(SB)
        admin-handlers.go:263   0x7f296 488b442408              MOVQ 0x8(SP), AX
        admin-handlers.go:263   0x7f29b 48898424b8000000        MOVQ AX, 0xb8(SP)
        admin-handlers.go:263   0x7f2a3 48c70000000000          MOVQ $0x0, 0(AX)
        admin-handlers.go:263   0x7f2aa 48c7400800000000        MOVQ $0x0, 0x8(AX)
        admin-handlers.go:266   0x7f2b2 488b0dbfa90701          MOVQ 0x107a9bf(IP), CX
        admin-handlers.go:266   0x7f2b9 48894c2478              MOVQ CX, 0x78(SP)
        admin-handlers.go:266   0x7f2be 488b15aba90701          MOVQ 0x107a9ab(IP), DX
        admin-handlers.go:266   0x7f2c5 31db                    XORL BX, BX
        admin-handlers.go:266   0x7f2c7 48895c2470              MOVQ BX, 0x70(SP)
        admin-handlers.go:266   0x7f2cc 48899424b0000000        MOVQ DX, 0xb0(SP)

TEXT github.com/minio/minio/cmd.(*adminAPIHandlers).ServerInfoHandler(SB) <autogenerated>
        <autogenerated>:4       0x1bc7d0        65488b0c25a0080000      GS MOVQ GS:0x8a0, CX
        <autogenerated>:4       0x1bc7d9        483b6110                CMPQ 0x10(CX), SP
        <autogenerated>:4       0x1bc7dd        0f86a6000000            JBE 0x1bc889
        <autogenerated>:4       0x1bc7e3        4883ec38                SUBQ $0x38, SP
        <autogenerated>:4       0x1bc7e7        48896c2430              MOVQ BP, 0x30(SP)
        <autogenerated>:4       0x1bc7ec        488d6c2430              LEAQ 0x30(SP), BP
        <autogenerated>:4       0x1bc7f1        488b5920                MOVQ 0x20(CX), BX
        <autogenerated>:4       0x1bc7f5        4885db                  TESTQ BX, BX
        <autogenerated>:4       0x1bc7f8        740d                    JE 0x1bc807
        <autogenerated>:4       0x1bc7fa        488d7c2440              LEAQ 0x40(SP), DI
        <autogenerated>:4       0x1bc7ff        48393b                  CMPQ DI, 0(BX)
        <autogenerated>:4       0x1bc802        7503                    JNE 0x1bc807
        <autogenerated>:4       0x1bc804        488923                  MOVQ SP, 0(BX)
        <autogenerated>:4       0x1bc807        488b442440              MOVQ 0x40(SP), AX
        <autogenerated>:4       0x1bc80c        4885c0                  TESTQ AX, AX
        <autogenerated>:4       0x1bc80f        7433                    JE 0x1bc844
        <autogenerated>:4       0x1bc811        488b442440              MOVQ 0x40(SP), AX
        <autogenerated>:4       0x1bc816        8400                    TESTB AL, 0(AX)
        <autogenerated>:4       0x1bc818        488b442448              MOVQ 0x48(SP), AX
        <autogenerated>:4       0x1bc81d        48890424                MOVQ AX, 0(SP)
        <autogenerated>:4       0x1bc821        488b442450              MOVQ 0x50(SP), AX
        <autogenerated>:4       0x1bc826        4889442408              MOVQ AX, 0x8(SP)
        <autogenerated>:4       0x1bc82b        488b442458              MOVQ 0x58(SP), AX
        <autogenerated>:4       0x1bc830        4889442410              MOVQ AX, 0x10(SP)
        <autogenerated>:4       0x1bc835        e88629ecff              CALL github.com/minio/minio/cmd.adminAPIHandlers.ServerInfoHandler(SB)
        <autogenerated>:4       0x1bc83a        488b6c2430              MOVQ 0x30(SP), BP
        <autogenerated>:4       0x1bc83f        4883c438                ADDQ $0x38, SP
        <autogenerated>:4       0x1bc843        c3                      RET
        <autogenerated>:4       0x1bc844        488d0519368300          LEAQ 0x833619(IP), AX
        <autogenerated>:4       0x1bc84b        48890424                MOVQ AX, 0(SP)
        <autogenerated>:4       0x1bc84f        48c744240803000000      MOVQ $0x3, 0x8(SP)
        <autogenerated>:4       0x1bc858        488d05d40f8400          LEAQ 0x840fd4(IP), AX
        <autogenerated>:4       0x1bc85f        4889442410              MOVQ AX, 0x10(SP)
        <autogenerated>:4       0x1bc864        48c744241810000000      MOVQ $0x10, 0x18(SP)
        <autogenerated>:4       0x1bc86d        488d05da238400          LEAQ 0x8423da(IP), AX
        <autogenerated>:4       0x1bc874        4889442420              MOVQ AX, 0x20(SP)
        <autogenerated>:4       0x1bc879        48c744242811000000      MOVQ $0x11, 0x28(SP)
        <autogenerated>:4       0x1bc882        e8b9c4e4ff              CALL runtime.panicwrap(SB)
        <autogenerated>:4       0x1bc887        eb88                    JMP 0x1bc811
        <autogenerated>:4       0x1bc889        e802dae9ff              CALL runtime.morestack_noctxt(SB)
        <autogenerated>:4       0x1bc88e        e93dffffff              JMP github.com/minio/minio/cmd.(*adminAPIHandlers).ServerInfoHandler(SB)
TEXT github.com/minio/minio/cmd.(*adminAPIHandlers).ListLocksHandler(SB) <autogenerated>
        <autogenerated>:5       0x1bc8a0        65488b0c25a0080000      GS MOVQ GS:0x8a0, CX
        <autogenerated>:5       0x1bc8a9        483b6110                CMPQ 0x10(CX), SP
        <autogenerated>:5       0x1bc8ad        0f86a6000000            JBE 0x1bc959
        <autogenerated>:5       0x1bc8b3        4883ec38                SUBQ $0x38, SP
        <autogenerated>:5       0x1bc8b7        48896c2430              MOVQ BP, 0x30(SP)
        <autogenerated>:5       0x1bc8bc        488d6c2430              LEAQ 0x30(SP), BP
        <autogenerated>:5       0x1bc8c1        488b5920                MOVQ 0x20(CX), BX
        <autogenerated>:5       0x1bc8c5        4885db                  TESTQ BX, BX
        <autogenerated>:5       0x1bc8c8        740d                    JE 0x1bc8d7
        <autogenerated>:5       0x1bc8ca        488d7c2440              LEAQ 0x40(SP), DI
        <autogenerated>:5       0x1bc8cf        48393b                  CMPQ DI, 0(BX)
        <autogenerated>:5       0x1bc8d2        7503                    JNE 0x1bc8d7`
